### ISSUE TITLE
I just had a huge win with pysqlite3-binary

### ISSUE THREAD

**Issue by simonw** [coleifer/pysqlite3#11]
Just wanted to let you know how much trouble this saved me!

I've been working on getting Datasette to deploy to Zeit Now v2, which runs on top of AWS Lambda.

Lambda ships a REALLY old version of SQLite -  3.7.17 from 2013, which doesn't even have FTS5 or json1.

I was really struggling with this... and then I thought "could pysqlite3-binary work here?"

Turns out it fixed ALL of my problems! https://github.com/simonw/datasette-publish-now/issues/17

Here's a demo I just deployed: https://datasette-json-html.now.sh/demo/packages - see https://datasette-json-html.now.sh/-/versions for version info.

Just wanted to thank you and let you know that I really appreciate your work on this.

**Comment by coleifer** [comment]
I'm very glad that you've found the project useful. I appreciate your helpful suggestions over the past year or so as well (#2 for example).

**Comment by AbdealiJK** [comment]
Just wanted to say - that I also found this project due to the 3.7.x default sqlite in RHEL7 based distros
And this project saved me a lot of time and effort.
I plan to make this project the standard in all my sqlite usages when I need to isolate from OS level issues !
pysqlite3-binary was the saviour!
