### ISSUE TITLE
ICU extension support

### ISSUE THREAD

**Issue by karlb** [coleifer/pysqlite3#15]
Is the a specific reason why the [ICU extension](https://www.sqlite.org/src/artifact?ci=trunk&filename=ext/icu/README.txt) is not included along with the other "numerous extensions"?

Related to this, it would be helpful to have a list of included extensions in the README.

**Comment by coleifer** [comment]
The default mode for pysqlite3 is to link against the system library, so this question only really carries meaning when using the "build_static" subcommand. If you had followed the rest of the bit from the readme, it says:

>and requires no external dependencies

ICU is not built by default because it introduces a dependency. The extensions that are built in amalgamation-mode are all self-contained, so it simplifies the process for end-users. You can always specify additional extensions using CFLAGS when building pysqlite3 using "build_static" with the amalgamation if you wish, as the amalgamation includes the ICU code.
