### ISSUE TITLE
Feature Request:  Expose sqlite3_busy_handler to Python side

### ISSUE THREAD

**Issue by joelclark** [coleifer/pysqlite3#80]
Would it be possible to wire up sqlite3_busy_handler() so that Python busy handlers can be used?  

https://www.sqlite.org/c3ref/busy_handler.html

The Ruby folks have done a ton of research on how to use sqlite3 on production websites and it mostly revolves around the right pragmas and replacing the default busy wait with a fast wait loop.  I'd like to be able to do that on my Flask app as well.

I'd be willing to test and contribute as best I can.

**Comment by coleifer** [comment]
I'd be wary of anyone claiming to have a silver bullet. I'd also be wary of using a custom busy handler written in Python because it necessarily must acquire the GIL and hold it while calling your custom busy handler. For my own use, I wrote a custom "aggressive" busy handler (lol): https://github.com/coleifer/peewee/blob/master/playhouse/_sqlite_ext.pyx#L1604-L1629

The idea with the above code, as the comment indicates, is that oftentimes concurrent queries are kicked-off around the same time which can cause the connections wanting the lock to proceed in lockstep -- so instead we add some random jitter along w/more "attempts" in a given interval of time. The above code also does *NOT* acquire the GIL, being implemented in C only.

Here you can see the default sqlite3 busy handler to get an idea of the difference:

https://github.com/sqlite/sqlite/blob/afb879858067f0fda250ffa0a5762e62c4d16a64/src/main.c#L1688-L1729

Nonetheless, if you want a footgun because the toeless ruby guys have one, godspeed. Added:

* Connection.set_busy_handler(busy_handler) -> busy handler accepts a single integer argument, which is the number of times the handler has been invoked waiting for the lock. Return 0 to trigger SQLITE_BUSY else to keep trying.
* Connection.set_busy_timeout(int seconds) -> restore default busy handler w/the given timeout in seconds.

**Comment by joelclark** [comment]
First off, thank you for the super-fast turnaround.  It's truly appreciated.  

Definitely not looking for a footgun, will dig in a little further before I decide how to proceed.

Cheers!
